name: package

on:
  release:
    types: [ 'published' ]

permissions:
  contents: write

jobs:
  deploy:

    runs-on: ubuntu-latest # ubuntu-22.04

    steps:
    - uses: actions/checkout@v4.1.0
      with:
        lfs: false # 不下载Git LFS缓存.
    - name: Set up Python
      uses: actions/setup-python@v4.7.1
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Publish package to Releases
      uses: softprops/action-gh-release@v0.1.15
      with:
        files: |
          dist/*.whl
